### ISSUE TITLE
Initial setup todo

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/devtools#5]
# Kubernetes

- [x] Configure [system-upgrade-controller](https://docs.k3s.io/upgrades/automated)
- [ ] Set up preview environments controller
- [x] Move discord bot
